# Generated by Django 5.2.1 on 2025-06-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Draft', 'draft'), ('Published', 'published')], default='draft', max_length=10),
        ),
    ]
